[package]
name = "robotica-types"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13"
prost-reflect = { version = "0.14", features = ["derive", "serde", "text-format"] }
prost-types = "0.13"

[build-dependencies]
anyhow = "1"
prost-build = "0.13"
prost-reflect-build = "0.14"
