[package]
name = "robotica-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
robotica = { version = "0.1", path = ".." }
serde_json = "1.0"
tokio = "1.43"
