name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install prerequisites
      run: sudo apt-get install -y protobuf-compiler
    - name: Format
      run: cargo fmt --check
    - name: Clippy checks
      run: cargo clippy --verbose -- -D warnings -D clippy::all -D clippy::pedantic
    - name: Build
      run: cargo build --all-targets --verbose
    - name: Run tests
      run: cargo test --verbose

